class IndustryData {
  final List<String> industries = [
    'Agriculture & Agribusiness',
    'Construction & Real Estate',
    'Manufacturing & Industrial',
    'Textile & Garment',
    'Leather & Footwear',
    'Mining & Metals',
    'Energy & Utilities',
    'Water & Sanitation',
    'Information Technology (IT)',
    'Telecommunications',
    'Banking & Financial Services',
    'Insurance',
    'Microfinance & SACCOs',
    'Retail & Wholesale',
    'Import & Export',
    'Logistics & Supply Chain',
    'Transportation',
    'Travel & Tourism',
    'Hospitality & Hotels',
    'Food & Beverage',
    'Education & Training',
    'Healthcare & Pharmaceuticals',
    'Media & Entertainment',
    'Legal & Consultancy',
    'Non-Governmental Organizations (NGOs)',
    'Government & Public Administration',
    'Security & Protection Services',
    'Environmental & Conservation',
    'Creative Arts & Design',
    'Science & Research',
    'Engineering & Technical Services',
    'Automotive & Vehicle Maintenance',
    'Waste Management',
    'Religious & Faith-Based Organizations',
    'Printing & Publishing',
    'Professional Services',
    'Call Center & BPO',
    'Real Estate Development & Management',
    'E-commerce & Online Services',
    'Sport & Recreation',
    'Fashion & Beauty',
    'Aviation & Airlines',
    'Maritime & Shipping',
    'Event Management',
    'Social Enterprises',
    'Others'
  ];
}
