class SkillsData{

  static final List<String> allSkills = [
  'Flutter',
  'Dart',
  'Firebase',
  'JavaScript',
  'TypeScript',
  'React',
  'React Native',
  'Node.js',
  'Python',
  'Java',
  'Kotlin',
  'Swift',
  'iOS Development',
  'Android Development',
  'UI/UX Design',
  'Figma',
  'Adobe XD',
  'Graphic Design',
  'HTML',
  'CSS',
  'Bootstrap',
  'Tailwind CSS',
  'PHP',
  'Laravel',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Git',
  'GitHub',
  'GitLab',
  'Docker',
  'Kubernetes',
  'AWS',
  'Google Cloud',
  'Azure',
  'RESTful APIs',
  'GraphQL',
  'CI/CD',
  'Agile Methodology',
  'Scrum',
  'Project Management',
  'Leadership',
  'Teamwork',
  'Communication',
  'Problem Solving',
  'Critical Thinking',
  'Time Management',
  'Customer Service',
  'Sales',
  'Marketing',
  'Content Writing',
  'SEO',
  'Digital Marketing',
  'Social Media Management',
  'Data Analysis',
  'Machine Learning',
  'Artificial Intelligence',
  'Blockchain',
  'Smart Contracts',
  'Solidity',
  'Web3',
  'Cybersecurity',
  'Network Security',
  'Ethical Hacking',
  'DevOps',
  'Linux',
  'Windows Server',
  'System Administration',
  'Cloud Computing',
  'Big Data',
  'Data Science',
  'Business Analysis',
  'Financial Analysis',
  'Accounting',
  'Human Resources',
  'Recruiting',
  'Training',
  'Public Speaking',
  'Negotiation',
  'Conflict Resolution',
  'Creativity',
  'Adaptability',
  'Attention to Detail',
  'Organization',
  'Multitasking',
  'Decision Making',
  'Strategic Planning',
  'Quality Assurance',
  'Testing',
  'Debugging',
  'Technical Writing',
  'Documentation',
  'Mentoring',
  'Coaching',
  'Research',
  'Data Entry',
  'Microsoft Office',
  'Excel',
  'PowerPoint',
  'Word',
  'Google Workspace',
  'Slack',
  'Trello',
  'Asana',
  'Jira',
  'Confluence',
  'Zapier',
  'Automation',
  'Customer Relationship Management (CRM)',
  'Salesforce',
  'HubSpot',
  'Email Marketing',
  'Copywriting',
  'Translation',
  'Interpreting',
  'Event Planning',
  'Logistics',
  'Supply Chain Management',
  'Inventory Management',
  'E-commerce',
  'Shopify',
  'WooCommerce',
  'WordPress',
  'Web Development',
  'Mobile Development',
  'Game Development',
  'Unity',
  'Unreal Engine',
  '3D Modeling',
  'Blender',
  'Maya',
  'Photoshop',
  'Illustrator',
  'Premiere Pro',
  'After Effects',
  'Video Editing',
  'Motion Graphics',
  'Photography',
  'Videography',
  'Audio Production',
  'Music Composition',
  'Sound Design',
  'Podcasting',
  'Animation',
  'Illustration',
  'Drawing',
  'Painting',
  'Sculpting',
  'Print Design',
  'Packaging Design',
  'Branding',
  'Logo Design',
  'Typography',
  'Color Theory',
  'User Research',
  'Usability Testing',
  'Wireframing',
  'Prototyping',
  'Information Architecture',
  'Interaction Design',
  'Visual Design',
  'Responsive Design',
  'Accessibility',
  'Localization',
  'Internationalization',
  'Performance Optimization',
  'Security',
  'Scalability',
  'Microservices',
  'Serverless',
  'IoT',
  'Embedded Systems',
  'Arduino',
  'Raspberry Pi',
  'Robotics',
  'Computer Vision',
  'Natural Language Processing',
  'Chatbots',
  'Virtual Reality',
  'Augmented Reality',
  'Mixed Reality',
  'Quantum Computing',
  'Bioinformatics',
  'Computational Biology',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Statistics',
  'Econometrics',
  'Actuarial Science',
  'Risk Management',
  'Compliance',
  'Legal',
  'Regulatory Affairs',
  'Healthcare',
  'Medicine',
  'Nursing',
  'Pharmacy',
  'Dentistry',
  'Veterinary',
  'Agriculture',
  'Environmental Science',
  'Sustainability',
  'Renewable Energy',
  'Architecture',
  'Civil Engineering',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Chemical Engineering',
  'Industrial Engineering',
  'Aerospace Engineering',
  'Automotive Engineering',
  'Manufacturing',
  'Quality Control',
  'Operations',
  'Supply Chain',
  'Procurement',
  'Vendor Management',
  'Contract Management',
  'Public Relations',
  'Media',
  'Journalism',
  'Broadcasting',
  'Film',
  'Television',
  'Theater',
  'Dance',
  'Acting',
  'Singing',
  'Music Production',
  'Audio Engineering',
  'Live Sound',
  'Lighting',
  'Stage Management',
  'Costume Design',
  'Set Design',
  'Makeup Artistry',
  'Hair Styling',
  'Fashion Design',
  'Textile Design',
  'Jewelry Design',
  'Product Design',
  'Industrial Design',
  'Furniture Design',
  'Interior Design',
  'Landscape Architecture',
  'Urban Planning',
  'Geographic Information Systems (GIS)',
  'Cartography',
  'Surveying',
  'Construction',
  'Real Estate',
  'Property Management',
  'Appraisal',
  'Mortgage',
  'Insurance',
  'Banking',
  'Finance',
  'Investment',
  'Trading',
  'Cryptocurrency',
  'Forex',
  'Commodities',
  'Derivatives',
  'Hedge Funds',
  'Private Equity',
  'Venture Capital',
  'Startups',
  'Entrepreneurship',
  'Business Development',
  'Partnerships',
  'Fundraising',
  'Grants',
  'Nonprofit',
  'Philanthropy',
  'Social Work',
  'Counseling',
  'Psychology',
  'Psychiatry',
  'Therapy',
  'Coaching',
  'Life Coaching',
  'Career Coaching',
  'Executive Coaching',
  'Leadership Development',
  'Diversity and Inclusion',
  'Human Rights',
  'Advocacy',
  'Policy',
  'Government',
  'Public Administration',
  'Diplomacy',
  'International Relations',
  'Political Science',
  'Economics',
  'Sociology',
  'Anthropology',
  'History',
  'Philosophy',
  'Theology',
  'Religion',
  'Languages',
  'Linguistics',
  'Literature',
  'Creative Writing',
  'Poetry',
  'Fiction',
  'Nonfiction',
  'Editing',
  'Publishing',
  'Library Science',
  'Archival',
  'Museums',
  'Cultural Heritage',
  'Archaeology',
  'Paleontology',
  'Geology',
  'Meteorology',
  'Oceanography',
  'Astronomy',
  'Astrophysics',
  'Cosmology',
  'Education',
  'Teaching',
  'Curriculum Development',
  'Instructional Design',
  'E-learning',
  'Educational Technology',
  'Special Education',
  'Early Childhood Education',
  'Higher Education',
  'Vocational Training',
  'Adult Education',
  'Literacy',
  'Numeracy',
  'STEM',
  'STEAM',
  'Coding',
  'Robotics',
  'Artificial Intelligence',
  'Virtual Reality',
  'Augmented Reality',
  'Gamification',
  'Pedagogy',
  'Andragogy',
  'Assessment',
  'Evaluation',
  'Accreditation',
  'Quality Assurance',
  'Compliance',
  'Regulatory Affairs',
  'Health and Safety',
  'Environmental Health',
  'Occupational Health',
  'Public Health',
  'Epidemiology',
  'Biostatistics',
  'Health Informatics',
  'Telemedicine',
  'Healthcare Administration',
  'Hospital Management',
  'Clinical Research',
  'Drug Development',
  'Pharmacovigilance',
  'Medical Writing',
  'Medical Coding',
  'Medical Billing',
  'Medical Transcription',
  'Medical Illustration',
  'Medical Photography',
  'Medical Devices',
  'Biomedical Engineering',
  'Tissue Engineering',
  'Regenerative Medicine',
  'Stem Cells',
  'Genetics',
  'Genomics',
  'Proteomics',
  'Metabolomics',
  'Bioengineering',
  'Biotechnology',
  'Pharmaceuticals',
  'Vaccines',
  'Immunology',
  'Virology',
  'Bacteriology',
  'Parasitology',
  'Mycology',
  'Microbiology',
  'Molecular Biology',
  'Cell Biology',
  'Developmental Biology',
  'Evolutionary Biology',
  'Ecology',
  'Conservation',
  'Wildlife',
  'Marine Biology',
  'Zoology',
  'Botany',
  'Plant Science',
  'Agriculture',
  'Horticulture',
  'Forestry',
  'Soil Science',
  'Hydrology',
  'Climatology',
  'Atmospheric Science',
  'Environmental Science',
  'Sustainability',
  'Renewable Energy',
  'Clean Technology',
  'Green Building',
  'Circular Economy',
  'Corporate Social Responsibility',
  'Ethical Sourcing',
  'Fair Trade',
  'Social Entrepreneurship',
  'Impact Investing',
  'Microfinance',
  'Community Development',
  'Rural Development',
  'Urban Development',
  'Housing',
  'Transportation',
  'Logistics',
  'Supply Chain',
  'Procurement',
  'Inventory',
  'Warehousing',
  'Distribution',
  'Retail',
  'E-commerce',
  'Marketplaces',
  'Platforms',
  'SaaS',
  'PaaS',
  'IaaS',
  'Cloud Computing',
  'Edge Computing',
  'Quantum Computing',
  'Blockchain',
  'Cryptography',
  'Cybersecurity',
  'Information Security',
  'Network Security',
  'Application Security',
  'Data Privacy',
  'GDPR',
  'Compliance',
  'Risk Management',
  'Business Continuity',
  'Disaster Recovery',
  'Incident Response',
  'Forensics',
  'Penetration Testing',
  'Ethical Hacking',
  'Threat Intelligence',
  'Vulnerability Management',
  'Security Operations',
  'Governance',
  'Audit',
  'Controls',
  'Policies',
  'Standards',
  'Frameworks',
  'ISO',
  'NIST',
  'PCI',
  'HIPAA',
  'SOC',
  'GDPR',
  'CCPA',
  'LGPD',
  'PIPEDA',
  'Data Protection',
  'Privacy',
  'Consent',
  'Transparency',
  'Accountability',
  'Ethics',
  'Responsibility',
  'Sustainability',
  'ESG',
  'DEI',
  'Diversity',
  'Equity',
  'Inclusion',
  'Belonging',
  'Accessibility',
  'Universal Design',
  'Inclusive Design',
  'Human-Centered Design',
  'Design Thinking',
  'Systems Thinking',
  'Complexity',
  'Chaos',
  'Uncertainty',
  'Risk',
  'Opportunity',
  'Innovation',
  'Creativity',
  'Ideation',
  'Brainstorming',
  'Prototyping',
  'Testing',
  'Iteration',
  'Improvement',
  'Optimization',
  'Efficiency',
  'Productivity',
  'Performance',
  'Metrics',
  'Analytics',
  'Insights',
  'Visualization',
  'Reporting',
  'Dashboards',
  'KPIs',
  'OKRs',
  'ROI',
  'Value',
  'Impact',
  'Outcomes',
  'Outputs',
  'Inputs',
  'Processes',
  'Workflows',
  'Automation',
  'RPA',
  'AI',
  'ML',
  'NLP',
  'CV',
  'Robotics',
  'IoT',
  'Digital Twins',
  'Simulation',
  'Modeling',
  'Prediction',
  'Forecasting',
  'Trends',
  'Patterns'
];
}